device_actions:
- id: e2e_log_action
  name: Logs a statement to indicate the device action was executed.
  tradefed_target_preparers:
  - class_name: com.android.tradefed.targetprep.RunHostCommandTargetPreparer
    option_values:
    - name: host-setup-command
      values:
      - echo "Executing e2e_log_action on device $SERIAL"

- id: connect_wifi
  name: wifi connect
  tradefed_options:
  - name: wifi-network
    values:
    - wifi-name
  - name: wifi-psk
    values:
    - abcd
  - name: wifi
    values:
    - 'ON'
  - name: force-skip-system-props
    values:
    - 'true'
  - name: disconnect-wifi-after-test
    values:
    - 'false'
  - name: max-wifi-connect-time
    values:
    - '100000'
  tradefed_target_preparers:
  - class_name: com.android.tradefed.targetprep.DeviceSetup


tests:
- id: e2e_fake_test
  name: Custom test suite which executes a fake test.
  command: host --class com.android.tradefed.testtype.FakeTest
